package(default_visibility = ["//visibility:public"])

java_library(
name = "mainservice",
srcs = glob(["src/main/java/com/github/yeshamavani/main/*.java"]),
runtime_deps = ["//packages/core:corelibrary"],
visibility = ["//visibility:public"]
)

